name: rl
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - archspec=0.2.5=pyhd3eb1b0_0
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - boltons=25.0.0=py312h06a4308_0
  - brotlicffi=1.1.0.0=py312hbdd6827_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.11.4=h06a4308_0
  - certifi=2025.11.12=py312h06a4308_0
  - cffi=2.0.0=py312h4eded50_1
  - charset-normalizer=3.4.4=py312h06a4308_0
  - conda=25.9.1=py312h06a4308_0
  - conda-libmamba-solver=25.4.0=pyhdf14ebd_1
  - conda-package-handling=2.4.0=py312h06a4308_1
  - conda-package-streaming=0.12.0=py312h06a4308_1
  - cpp-expected=1.1.0=hdb19cb5_0
  - cuda-cccl_linux-64=12.8.90=h06a4308_1
  - cuda-crt-dev_linux-64=12.8.93=h06a4308_3
  - cuda-crt-tools=12.8.93=h06a4308_3
  - cuda-cudart=12.8.90=hbdd6827_0
  - cuda-cudart-dev=12.8.90=hbdd6827_0
  - cuda-cudart-dev_linux-64=12.8.90=hd1a145a_0
  - cuda-cudart-static=12.8.90=hbdd6827_0
  - cuda-cudart-static_linux-64=12.8.90=hd1a145a_0
  - cuda-cudart_linux-64=12.8.90=hd1a145a_0
  - cuda-driver-dev_linux-64=12.8.90=hd1a145a_0
  - cuda-nvcc=12.8.93=0
  - cuda-nvcc-dev_linux-64=12.8.93=he2511ca_3
  - cuda-nvcc-impl=12.8.93=hd1a145a_3
  - cuda-nvcc-tools=12.8.93=hbdd6827_3
  - cuda-nvcc_linux-64=12.8.93=h2f703a9_2
  - cuda-nvrtc=12.8.93=hbdd6827_1
  - cuda-nvvm-dev_linux-64=12.8.93=h06a4308_3
  - cuda-nvvm-impl=12.8.93=hbdd6827_3
  - cuda-nvvm-tools=12.8.93=hbdd6827_3
  - cuda-version=12.8=h30beaf8_3
  - cudnn=9.10.1.4=hbcb9cd8_1
  - distro=1.9.0=py312h06a4308_0
  - expat=2.7.3=h3385a95_0
  - fmt=11.2.0=hca5f364_0
  - frozendict=2.4.6=py312hee96239_0
  - gcc_impl_linux-64=14.3.0=h4943218_4
  - gcc_linux-64=14.3.0=hda73cce_11
  - gettext=0.21.0=hedfda30_2
  - gxx_impl_linux-64=14.3.0=he634eba_4
  - gxx_linux-64=14.3.0=hca8765c_11
  - icu=73.1=h6a678d5_0
  - idna=3.11=py312h06a4308_0
  - jansson=2.14=h5eee18b_1
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=3.0.0=py312h06a4308_0
  - kernel-headers_linux-64=4.18.0=h3108a97_1
  - ld_impl_linux-64=2.44=h153f514_2
  - libarchive=3.8.2=h3ec8f01_0
  - libcublas=12.8.4.1=hbdd6827_1
  - libcudnn=9.10.1.4=hf7e9902_1
  - libcudnn-dev=9.10.1.4=h58dd1b1_1
  - libcurl=8.16.0=heebcbe5_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=14.3.0=he7458c1_104
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libmamba=2.3.2=h860b5fb_1
  - libmambapy=2.3.2=py312h3f77f5b_1
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.0=h5eee18b_0
  - libsanitizer=14.3.0=hd4faa28_4
  - libsolv=0.7.30=h6f1ccf3_2
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=14.3.0=he7458c1_104
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - menuinst=2.4.1=py312h06a4308_1
  - ncurses=6.5=h7934f7d_0
  - nlohmann_json=3.11.2=h6a678d5_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py312h06a4308_1
  - pcre2=10.46=hf426167_0
  - pip=25.3=pyhc872135_0
  - platformdirs=4.5.0=py312h06a4308_0
  - pluggy=1.5.0=py312h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h5eee18b_2
  - pycparser=2.23=py312h06a4308_0
  - pysocks=1.7.1=py312h06a4308_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.5=py312h06a4308_1
  - ruamel.yaml=0.18.16=py312h4aee224_0
  - ruamel.yaml.clib=0.2.14=py312h4aee224_0
  - simdjson=3.10.1=hdb19cb5_0
  - sqlite=3.51.0=h2a70700_0
  - sysroot_linux-64=2.28=h3108a97_1
  - tk=8.6.15=h54e0aa7_0
  - tqdm=4.67.1=py312h7040dfc_1
  - truststore=0.10.1=py312h06a4308_1
  - urllib3=2.5.0=py312h06a4308_0
  - uv=0.9.10=h76e24b7_0
  - wheel=0.45.1=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.3.1=hb25bd0a_0
  - zstandard=0.24.0=py312h3d778a8_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - airportsdata==20250909
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.75.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - astor==0.8.1
      - asttokens==3.0.1
      - attrs==25.4.0
      - av==16.0.1
      - blake3==1.0.8
      - blobfile==3.0.0
      - build==1.3.0
      - cachetools==6.2.3
      - cbor2==5.7.1
      - cfgv==3.5.0
      - click==8.2.1
      - cloudpickle==3.1.2
      - codetiming==1.4.0
      - colorful==0.5.8
      - compressed-tensors==0.11.0
      - cuda-bindings==13.1.1
      - cuda-pathfinder==1.3.3
      - cuda-python==13.1.1
      - cupy-cuda12x==13.6.0
      - datasets==4.4.1
      - decorator==5.2.1
      - decord==0.6.0
      - depyf==0.19.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distlib==0.4.0
      - dnspython==2.8.0
      - docstring-parser==0.17.0
      - einops==0.8.1
      - email-validator==2.3.0
      - executing==2.2.1
      - fastapi==0.124.4
      - fastapi-cli==0.0.16
      - fastapi-cloud-cli==0.6.0
      - fastar==0.8.0
      - fastrlock==0.8.3
      - filelock==3.20.0
      - flash-attn==2.8.1
      - flashinfer-python==0.3.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - gguf==0.17.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - google-api-core==2.28.1
      - google-auth==2.43.0
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - identify==2.6.15
      - importlib-metadata==8.7.0
      - iniconfig==2.3.0
      - interegular==0.3.3
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - lark==1.2.2
      - liger-kernel==0.6.4
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - lxml==6.0.2
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - mathruler==0.1.0
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mistral-common==1.8.6
      - modelscope==1.33.0
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - ninja==1.13.0
      - nodeenv==1.9.1
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.16.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.590.44
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - openai==1.99.1
      - openai-harmony==0.0.4
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-fixer==0.2.5
      - opencv-python==4.12.0.88
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-prometheus==0.60b1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - optree==0.18.0
      - orjson==3.11.5
      - outlines==0.1.11
      - outlines-core==0.2.11
      - pandas==2.3.3
      - parso==0.8.5
      - partial-json-parser==0.2.1.1.post7
      - peft==0.18.0
      - pexpect==4.9.0
      - pillow==12.0.0
      - pre-commit==4.5.0
      - prettytable==3.17.0
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.26.1
      - protobuf==6.33.2
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - py-spy==0.4.1
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pybase64==1.4.3
      - pybind11==3.0.1
      - pycountry==24.6.1
      - pycryptodomex==3.23.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pyecharts==2.0.9
      - pygments==2.19.2
      - pylatexenc==2.10
      - pyproject-hooks==1.2.0
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyvers==0.1.0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qwen-vl-utils==0.0.14
      - ray==2.52.1
      - referencing==0.37.0
      - regex==2025.11.3
      - rich==13.9.4
      - rich-toolkit==0.17.0
      - rignore==0.7.6
      - rpds-py==0.30.0
      - rsa==4.9.1
      - ruff==0.14.9
      - safetensors==0.7.0
      - scipy==1.16.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.47.0
      - setproctitle==1.3.7
      - setuptools==79.0.1
      - sgl-kernel==0.3.9.post2
      - sglang==0.5.2
      - shellingham==1.5.4
      - simplejson==3.20.2
      - six==1.17.0
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soxr==1.0.0
      - stack-data==0.6.3
      - starlette==0.50.0
      - swanlab==0.7.4
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensordict==0.10.0
      - tiktoken==0.12.0
      - timm==1.0.16
      - tokenizers==0.22.1
      - torch==2.8.0
      - torch-memory-saver==0.0.8
      - torchao==0.9.0
      - torchaudio==2.8.0
      - torchdata==0.11.0
      - torchvision==0.23.0
      - traitlets==5.14.3
      - transformers==4.56.1
      - triton==3.4.0
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - verl==0.7.0.dev0
      - virtualenv==20.35.4
      - vllm==0.11.0
      - wandb==0.23.1
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - websockets==15.0.1
      - werkzeug==3.1.4
      - wrapt==2.0.1
      - xformers==0.0.32.post1
      - xgrammar==0.1.25
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /mnt/parallel_ssd/home/zdhs0124/miniconda3/envs/rl
